import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";


interface Props {
    children: React.ReactNode;
}

const Layout: React.FC<Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Spot-Jobs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Row className="justify-content-center">
                    <Col>
                        {children}
                    </Col>
                </Row>
            </Container>

        </>
    )
}

export default Layout